#*******************************************************************************
# QMetry Automation Framework provides a powerful and versatile platform to author
# Automated Test Cases in Behavior Driven, Keyword Driven or Code Driven approach
#
# Copyright 2016 Infostretch Corporation
#
# This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or any later version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT
# OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE
#
# You should have received a copy of the GNU General Public License along with this program in the name of LICENSE.txt in the root folder of the distribution. If not, see https://opensource.org/licenses/gpl-3.0.html
#
# See the NOTICE.TXT file in root folder of this source files distribution
# for additional information regarding copyright ownership and licenses
# of other open source software / files used by QMetry Automation Framework.
#
# For any inquiry or need additional information, please contact support-qaf@infostretch.com
#******************************************************************************
test.prop = prop for env1

#Provide base URL of application under test
env.baseurl=

#set appropriate teststep provider package
step.provider.pkg=

#you can override this property from config file by providing "browser" parameter

driver.name=flutterDriver

#[Appium - Local] 
remote.server=127.0.0.1
remote.port=4723
#flutter.additional.capabilities= {'app':'/Users/uie27734/VSCodeProjects/flutter_application_1/build/app/outputs/flutter-apk/app-profile.apk','deviceName':'LMG850EMW0c9defb6','platformName':'Android','automationName':'Flutter','driverClass':'io.appium.java_client.android.AndroidDriver','retryBackoffTime':'2000','maxRetryCount':'5'}
#flutter.additional.capabilities= {'deviceName':'iPhone 15','platformName':'IOS','automationName':'Flutter',"udid":"3255ECE3-D606-4A6F-8628-D8F8F701DEC9","bundleId":"com.codecraft.conti",'driverClass':'io.appium.java_client.ios.IOSDriver',"platformVersion":"17.0",'retryBackoffTime':'2000','maxRetryCount':'5'}
#flutter.additional.capabilities= {'deviceName':'RZ8M30TG9DL','platformName':'Android','automationName':'Flutter',"appPackage":"net.dextracontiplus.dev",'driverClass':'io.appium.java_client.android.AndroidDriver',"platformVersion":"11.0",'retryBackoffTime':'2000','maxRetryCount':'5',"newCommandTimeout": '180',"app":"/Users/ostan/Documents/Automation/ctp-contiplus-web-qa-automation-java/resources/app-dev-debug1.apk"}
#flutter.additional.capabilities= {'deviceName':'Developer iPad','platformName':'IOS','automationName':'Flutter',"udid":"00008103-0018106901E9401E","bundleId":"com.codecraft.conti",'driverClass':'io.appium.java_client.ios.IOSDriver',"platformVersion":"16.4.1",'retryBackoffTime':'2000','maxRetryCount':'5',"app":"/Users/ostan/Documents/Automation/Cont+/ctp-contiplus-flutter-app/contiplus/build/ios/Profile-dev-iphoneos/Runner.app"}

##[Appium - Perfecto]
#perfecto.cloud=continental-public
#remote.server=https://${perfecto.cloud}.perfectomobile.com/nexperience/perfectomobile/wd/hub
#remote.port=80
#appium.capabilities.app=PUBLIC:app-uat.apk

##Connect to Perfecto mobile using session id(Preferred)
#appium.additional.capabilities= {'deviceSessionId':'deviceSessionId','securityToken':'securityToken','autoLaunch':false,'automationName'='Appium','platformName':'Android','driverClass':'io.appium.java_client.android.AndroidDriver'}

#Connect to Perfecto mobile using Device Name
#appium.additional.capabilities= {'deviceName':'deviceName','securityToken':'securityToken','autoLaunch':false,'automationName'='Appium','platformName':'Android','driverClass':'io.appium.java_client.android.AndroidDriver'}

#application name is must for execution. i.e. bundleId
aut.appName=net.dextracontiplus.dev

#Set this property to true and provide the updated apk path if you need to update app before launching
aut.updateApp=false
#aut.path=/Users/ostan/Downloads/QAF_FLUTTER-master/resources/Runner.app
aut.path=/Users/ostan/Documents/Automation/ctp-contiplus-web-qa-automation-java/resources/app-dev-debug.apk

#Set this property to true if you want to clear app cache before launching
aut.clearCache=false

#andriod specific timeouts. Check online for more details
android.apk.keyInjectionDelay=100
android.apk.waitForIdleTimeout=2000
android.apk.waitForSelectorTimeout=1000

#Enable below property to disable web driver manager
manage.driver.executable=false

#No of seconds fullter element will wait before timeout
flutter.wait.timeout=5

