#*******************************************************************************
# QMetry Automation Framework provides a powerful and versatile platform to author
# Automated Test Cases in Behavior Driven, Keyword Driven or Code Driven approach
#
# Copyright 2016 Infostretch Corporation
#
# This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or any later version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT
# OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE
#
# You should have received a copy of the GNU General Public License along with this program in the name of LICENSE.txt in the root folder of the distribution. If not, see https://opensource.org/licenses/gpl-3.0.html
#
# See the NOTICE.TXT file in root folder of this source files distribution
# for additional information regarding copyright ownership and licenses
# of other open source software / files used by QMetry Automation Framework.
#
# For any inquiry or need additional information, please contact support-qaf@infostretch.com
#******************************************************************************
test.prop = prop for env1

#Provide base URL of application under test
env.baseurl=

driver.name=appiumDriver

#[Appium - Perfecto]
perfecto.cloud=continental-public
remote.server=https://${perfecto.cloud}.perfectomobile.com/nexperience/perfectomobile/wd/hub
remote.port=80

appium.capabilities.app=PUBLIC:InvoiceApp1.0.ipa

#Connect to Perfecto mobile using session id(Preferred)
appium.additional.capabilities= {'deviceSessionId':'deviceSessionId','securityToken':'securityToken','autoLaunch':false,'platformName':'iOS','enableAppiumBehavior':'true','driverClass':'io.appium.java_client.ios.IOSDriver'}

#Connect to Perfecto mobile using Device Name
#appium.additional.capabilities= {'deviceName':'deviceName','securityToken':'securityToken','autoLaunch':false,'platformName':'iOS','enableAppiumBehavior':'true','driverClass':'io.appium.java_client.ios.IOSDriver'}

#application name is must for execution. i.e. bundleId
aut.appName=com.apple.calculator

#Set this property to true and provide the updated apk path if you need to update app before launching
#aut - Application Under Test
aut.updateApp=false
aut.path=resources/apps/InvoiceApp1.0.ipa

#Set this property to true if you want to clear app cache before launching
aut.clearCache=true



