name: web_automation_ci_test
on: 
  workflow_dispatch:
    inputs:
      app_env:
        description: 'Environment to run tests against'
        required: true
        default: 'stg'
    secrets:
      EMAIL_USERNAME:
        description: 'Email username for SMTP authentication'
      EMAIL_PASSWORD:
        description: 'Email password for SMTP authentication'
  push:
    branches:
      - workflows
jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: 'oracle'
          java-version: '21'
      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.8.2
      - name: print java version
        run: java -version
      - name: print maven version
        run: mvn -version
      - name: cache maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: maven-${{ hashFiles('**/pom
      - name: Run Maven Tests
        uses: ./.github/actions/maven-test
      - name: Generate datetime
        id: dt
        shell: bash
        run: echo "now=$(TZ='Asia/Kolkata' date '+%Y/%m/%d %H:%M')" >> $GITHUB_OUTPUT
      - name: Read HTML report
        id: read_html
        run: |
          echo "html<<EOF" >> $GITHUB_OUTPUT
          cat test-results/customized-emailable-report.html >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
      - name: Send Email Notification
        uses: ./.github/actions/email-notification
        with:
          recipient: 'ostan@codecraft.co.in'
          subject: '[CI] Conti+ Test Automation Report - ${{ steps.dt.outputs.now }}'
          body: '${{ steps.read_html.outputs.html }}'
          email_username: ${{ secrets.EMAIL_USERNAME }}
          email_password: ${{ secrets.EMAIL_PASSWORD }}


    

